-- CryptoPulse — Rebuild Schema (Supabase + static)
-- Scope: Signals / TA / Trade (paper engine). Sizing = flat $1,000/trade.
-- Run once in Supabase SQL editor OR via the psql/service_role REST exec.

-- ══════════════════════════════════════════════════════════════
-- SIGNALS — generated by the TA pipeline
-- ══════════════════════════════════════════════════════════════
CREATE TABLE IF NOT EXISTS public.signals (
  id            BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  symbol        TEXT NOT NULL,
  direction     TEXT NOT NULL CHECK (direction IN ('BUY','SELL','NEUTRAL')),
  timeframe     TEXT NOT NULL DEFAULT '4H',
  entry_price   NUMERIC(18,8) NOT NULL,
  stop_loss     NUMERIC(18,8) NOT NULL,
  take_profit   NUMERIC(18,8) NOT NULL,
  risk_reward   NUMERIC(6,2),
  reason        TEXT,
  status        TEXT NOT NULL DEFAULT 'OPEN' CHECK (status IN ('OPEN','TP HIT','SL HIT','CLOSED')),
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (symbol, timeframe, created_at)
);
CREATE INDEX IF NOT EXISTS idx_signals_symbol ON public.signals (symbol);
CREATE INDEX IF NOT EXISTS idx_signals_created ON public.signals (created_at DESC);

-- ════════════════════════════════════════════════════════════════
-- PAPER_TRADES — auto-opened $1,000 virtual trade per signal
-- ════════════════════════════════════════════════════════════════
CREATE TABLE IF NOT EXISTS public.paper_trades (
  id            BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  signal_id     BIGINT REFERENCES public.signals(id) ON DELETE SET NULL,
  symbol        TEXT NOT NULL,
  direction     TEXT NOT NULL CHECK (direction IN ('BUY','SELL','NEUTRAL')),
  size_usd      NUMERIC(12,2) NOT NULL DEFAULT 1000.00,
  entry_price   NUMERIC(18,8) NOT NULL,
  stop_loss     NUMERIC(18,8) NOT NULL,
  take_profit   NUMERIC(18,8) NOT NULL,
  status        TEXT NOT NULL DEFAULT 'OPEN' CHECK (status IN ('OPEN','TP HIT','SL HIT')),
  exit_price    NUMERIC(18,8),
  pnl_usd       NUMERIC(12,2) DEFAULT 0,
  pnl_pct       NUMERIC(8,4) DEFAULT 0,
  opened_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
  closed_at     TIMESTAMPTZ,
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_paper_symbol ON public.paper_trades (symbol);
CREATE INDEX IF NOT EXISTS idx_paper_opened ON public.paper_trades (opened_at DESC);

-- ════════════════════════════════════════════════════════════════
-- PAIR_STATS — latest TA verdict per symbol (TA dashboard)
-- ════════════════════════════════════════════════════════════════
CREATE TABLE IF NOT EXISTS public.pair_stats (
  symbol        TEXT PRIMARY KEY,
  verdict       TEXT NOT NULL CHECK (verdict IN ('Bullish','Bearish','Neutral')),
  direction     TEXT NOT NULL CHECK (direction IN ('BUY','SELL','NEUTRAL')),
  rsi_1h        NUMERIC(6,2),
  rsi_4h        NUMERIC(6,2),
  rsi_1d        NUMERIC(6,2),
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ════════════════════════════════════════════════════════════════
-- PRICES — latest Binance prices (proxy-written, avoids browser CORS)
-- ════════════════════════════════════════════════════════════════
CREATE TABLE IF NOT EXISTS public.prices (
  symbol        TEXT PRIMARY KEY,
  price         NUMERIC(18,8) NOT NULL,
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ════════════════════════════════════════════════════════════════
-- VIRTUAL ACCOUNT — single row, running balance starts at $1,000
-- ════════════════════════════════════════════════════════════════
CREATE TABLE IF NOT EXISTS public.virtual_account (
  id            INT PRIMARY KEY DEFAULT 1 CHECK (id = 1),
  balance_usd   NUMERIC(14,2) NOT NULL DEFAULT 1000.00,
  realized_pnl  NUMERIC(14,2) NOT NULL DEFAULT 0,
  total_trades  INT NOT NULL DEFAULT 0,
  wins          INT NOT NULL DEFAULT 0,
  losses        INT NOT NULL DEFAULT 0,
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);
INSERT INTO public.virtual_account (id, balance_usd) VALUES (1, 1000.00)
  ON CONFLICT (id) DO NOTHING;

-- ════════════════════════════════════════════════════════════════
-- RLS — public read on everything (this is a public info site);
--        writes go through the service_role key (server-side proxy only)
-- ════════════════════════════════════════════════════════════════
ALTER TABLE public.signals        ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.paper_trades   ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.pair_stats     ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.prices         ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.virtual_account ENABLE ROW LEVEL SECURITY;

CREATE POLICY "public_read_signals"  ON public.signals  FOR SELECT USING (true);
CREATE POLICY "public_read_trades"   ON public.paper_trades FOR SELECT USING (true);
CREATE POLICY "public_read_stats"    ON public.pair_stats FOR SELECT USING (true);
CREATE POLICY "public_read_prices"   ON public.prices FOR SELECT USING (true);
CREATE POLICY "public_read_account"  ON public.virtual_account FOR SELECT USING (true);
